Description: Downloads the latest version of Docker, makes a pkg of it, and uploads to the JSS.
Identifier: com.github.team-dab.recipes.jamf.Docker-ARM64
MinimumVersion: "2.3"
ParentRecipe: com.github.smithjw.pkg.Docker

Input:
  NAME: Docker
  CATEGORY: Software - Licensed
  GROUP_NAME: "Patch Reporting: %NAME%-ARM64"
  GROUP_TEMPLATE: SmartGroupARM64JAMFTemplate.xml
  POLICY_CATEGORY: Automatic Patch Management
  POLICY_TEMPLATE: PolicyTemplateJAMF.xml
  POLICY_NAME: "Patch Management - Install Latest %NAME%-ARM64"
  SELFSERVICE_POLICY_CATEGORY: Software - Licensed
  SELFSERVICE_POLICY_TEMPLATE: SelfServicePolicyTemplateJAMFARM64.xml
  SELFSERVICE_POLICY_NAME: Software - Deploy %NAME%-ARM64 via Self Service
  SELFSERVICE_DESCRIPTION: Install the latest version of %NAME%-ARM64 on your device.
  SELFSERVICE_ICON: "%NAME%.png"
  ARCHITECTURE: arm64
  DOWNLOAD_TYPE: arm64
  UPDATE_PREDICATE: "pkg_uploaded == False"
  replace_policy: "True"
  replace_group: "True"

Process:
  - Processor: com.github.grahampugh.jamf-upload.processors/JamfCategoryUploader
    Arguments:
      category_name: "%CATEGORY%"
      
  - Processor: com.github.grahampugh.recipes.commonprocessors/VersionRegexGenerator

  - Processor: com.github.grahampugh.jamf-upload.processors/JamfPackageUploader
    Arguments:
      pkg_category: "%CATEGORY%"
  
  - Processor: StopProcessingIf
    Arguments:
      predicate: "%UPDATE_PREDICATE%"

  - Processor: com.github.grahampugh.jamf-upload.processors/JamfComputerGroupUploader
    Arguments:
      computergroup_template: "%GROUP_TEMPLATE%"
      computergroup_name: "%GROUP_NAME%"

  - Processor: com.github.grahampugh.jamf-upload.processors/JamfPolicyUploader
    Arguments:
      policy_template: "%POLICY_TEMPLATE%"
      policy_name: "%POLICY_NAME%"
      
  - Processor: com.github.grahampugh.jamf-upload.processors/JamfPolicyUploader
    Arguments:
      policy_template: "%SELFSERVICE_POLICY_TEMPLATE%"
      policy_name: "%SELFSERVICE_POLICY_NAME%"
      icon: "%SELFSERVICE_ICON%"